# Generated by Django 5.2 on 2025-04-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_emp_descrip', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nrodocumento', models.CharField(max_length=45)),
                ('cliente_tipodocumento', models.CharField(blank=True, max_length=45, null=True)),
                ('cliente_nombre', models.CharField(max_length=45)),
                ('cliente_paterno', models.CharField(max_length=45)),
                ('cliente_materno', models.CharField(max_length=45)),
                ('cliente_fechanac', models.DateField()),
                ('cliente_telefono', models.CharField(max_length=45)),
                ('cliente_email', models.CharField(blank=True, max_length=45, null=True)),
                ('cliente_sexo', models.CharField(blank=True, max_length=45, null=True)),
                ('cliente_direccion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDetEntrada',
            fields=[
                ('det_entrada_id', models.AutoField(primary_key=True, serialize=False)),
                ('det_entrada_cantidad', models.IntegerField()),
                ('det_entrada_precio_costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('det_entrada_sub_total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'tbl_det_entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDetFinanciamiento',
            fields=[
                ('det_finan_id', models.AutoField(primary_key=True, serialize=False)),
                ('det_finan_num_cuota', models.IntegerField()),
                ('det_finan_monto_cuota', models.DecimalField(decimal_places=2, max_digits=7)),
                ('det_finan_fch_pago_max', models.DateField()),
                ('det_finan_fch_pago_realiza', models.DateField(blank=True, null=True)),
                ('det_finan_estado_pago', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'tbl_det_financiamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDetSalida',
            fields=[
                ('det_salida_id', models.IntegerField(primary_key=True, serialize=False)),
                ('det_salida_cantidad', models.IntegerField(blank=True, null=True)),
                ('det_salida_precio_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('det_salida_sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'tbl_det_salida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDetVenta',
            fields=[
                ('det_venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('det_venta_cantidad', models.IntegerField()),
                ('det_venta_precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('det_venta_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('det_venta_dcto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('det_venta_total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'tbl_det_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEntrada',
            fields=[
                ('entrada_id', models.AutoField(primary_key=True, serialize=False)),
                ('entrada_fecha', models.DateTimeField()),
                ('entrada_costo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entrada_num_doc', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFinanciamiento',
            fields=[
                ('financia_id', models.AutoField(primary_key=True, serialize=False)),
                ('financia_monto_financiado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('financia_numero_cuotas', models.IntegerField()),
                ('financia_tasa_interes', models.DecimalField(decimal_places=2, max_digits=4)),
                ('financia_total_interes', models.DecimalField(decimal_places=2, max_digits=7)),
                ('financia_monto_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('financia_fecha_registro', models.DateField()),
                ('financia_estado', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'tbl_financiamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProducto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(max_length=25)),
                ('prod_modelo', models.CharField(max_length=45)),
                ('prod_motor', models.IntegerField()),
                ('prod_categoria', models.CharField(max_length=45)),
                ('prod_marca', models.CharField(max_length=45)),
                ('prod_aniofabricacion', models.TextField(blank=True, null=True)),
                ('prod_descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('prod_fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMetodoPago',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago_descrip', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor_nombre', models.CharField(max_length=100)),
                ('proveedor_ruc', models.CharField(max_length=45)),
                ('proveedor_telefono', models.CharField(max_length=45)),
                ('proveedor_direccion', models.CharField(max_length=45)),
                ('proveedor_email', models.CharField(max_length=45)),
                ('proveedor_prueba', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSalida',
            fields=[
                ('salida_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salida_fecha', models.DateField()),
                ('salida_costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salida_num_doc', models.IntegerField(blank=True, null=True)),
                ('salida_motivo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_salida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTipoDocAlmacen',
            fields=[
                ('tipo_doc_almacen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_doc_almacen_descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_tipo_doc_almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTipoUsuario',
            fields=[
                ('tipo_usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario_descrip', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUsuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nombreusuario', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_nrodocumento', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_tipodocumento', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_paterno', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_materno', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_fechanac', models.DateField(blank=True, null=True)),
                ('usuario_email', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_sexo', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'tbl_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVenta',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('venta_fecha_venta', models.DateTimeField()),
                ('venta_tipo_comprobante', models.CharField(max_length=7)),
                ('venta_monto_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('venta_subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('venta_igv', models.DecimalField(decimal_places=2, max_digits=8)),
                ('venta_total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'tbl_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblKardex',
            fields=[
                ('kardex_fecha_mov', models.DateTimeField()),
                ('kardex_cantidad_total_entrada', models.IntegerField(blank=True, null=True)),
                ('kardex_ultimo_precio_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('kardex_cantidad_total_salida', models.IntegerField(blank=True, null=True)),
                ('kardex_ultimo_precio_venta', models.DecimalField(blank=True, db_column='kardex_ultimo_ precio_venta', decimal_places=2, max_digits=7, null=True)),
                ('kardex_stock_actual', models.IntegerField()),
                ('kardex_precio_vigente', models.DecimalField(decimal_places=2, max_digits=7)),
                ('kardex_costo_total_saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kardex_stock_minimo', models.IntegerField()),
                ('kardex_porcentaje_utilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tienda.tblproducto')),
            ],
            options={
                'db_table': 'tbl_kardex',
                'managed': False,
            },
        ),
    ]
