# Generated by Django 5.2 on 2025-04-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblusuario',
            options={},
        ),
    ]
