# Generated by Django 5.2 on 2025-04-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_tblusuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblusuario',
            options={'managed': False},
        ),
    ]
